<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <StartupObject>MoneyTracker.Program</StartupObject>
    <AssemblyName>MoneyTracker</AssemblyName>
    <RootNamespace>MoneyTracker</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>
</Project>
